export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS= 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_SUCCESS= 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL= 'USER_UPDATE_FAIL';

export const COPARENT_REGISTER_REQUEST = 'COPARENT_REGISTER_REQUEST';
export const COPARENT_REGISTER_SUCCESS= 'COPARENT_REGISTER_SUCCESS';
export const COPARENT_REGISTER_FAIL= 'COPARENT_REGISTER_FAIL';

export const CHILD_REGISTER_REQUEST = 'CHILD_REGISTER_REQUEST';
export const CHILD_REGISTER_SUCCESS= 'CHILD_REGISTER_SUCCESS';
export const CHILD_REGISTER_FAIL= 'CHILD_REGISTER_FAIL';